In [19]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib, sys
matplotlib.use('TkAgg')
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk

class Process:
    arrival = 0
    burst = 0
    waiting = 0
    lastRunTime = 0
    priority = 0
    remainingTime = 0
    ID = 0
    finished = False
    started = False
    inQueue = False
    
    def __init__(self,arrival,burst,priority,ID):
        self.arrival = arrival
        self.burst = burst
        self.priority = priority
        self.remainingTime = burst
        self.ID = ID
        inQueue = False
        self.lastRunTime = 0
        
    def getTAT(self):
        return burst+waiting
    def getWTAT(self):
        return self.getTAT()/burst
    def start(self,currentTime):
        if(currentTime >= self.arrival):
            self.started = True
    def run(self,n):
        self.remainingTime -= n
        self.waiting += (n - self.lastRunTime)
        self.lastRunTime = n
        if (self.remainingTime <= 0):
            self.finished = True
            self.remainingTime = 0
    def wait(self,n):
        self.waitingTime += n
    def reset(self):
        self.waitingTime = 0
        self.remainingTime = self.burst
        self.finished = False
        self.started = False
        self.inQueue = False
        self.lastRunTime = 0
    def Print(self):
        print(self.ID,self.arrival,self.burst,self.priority)
    
        

inputs = np.array([])

with open("input.txt", "r") as file:
    for line in file:
        splitted = line.split( )
        inputs = np.append(inputs,splitted)

n = int(inputs[0])

colors = np.random.rand(n,3)
print(colors)

muArrival , sigmaArrival = float(inputs[1]), float(inputs[2])
muBurst , sigmaBurst = float(inputs[3]), float(inputs[4])
lamda = float(inputs[5])

Arrivals = np.random.normal(muArrival,sigmaArrival ,n)
Burst = np.random.normal(muBurst,sigmaBurst ,n)
Priority = np.random.poisson(lamda,n)
Waiting = np.zeros(Arrivals.shape)

contextSwitching = 5

fh = open("output.txt","w")

#Ouput to file the generated processes
for i in range(n):
    fh.write(str(i+1) + ' ' + str(Arrivals[i]) + ' ' + str(Burst[i]) + ' ' + str(Priority[i]) + '\n')

fh.close()


processes = np.array([range(n),Arrivals,Burst,Priority,Waiting]).transpose()
print('Original:')
print(processes)
print(' ')


[[0.09916621 0.43640965 0.65064797]
 [0.7925067  0.66995172 0.53796681]
 [0.98855168 0.80541769 0.37070399]
 [0.65916912 0.48385031 0.99438216]
 [0.42331262 0.14071725 0.78396695]
 [0.54364971 0.84258793 0.21116818]
 [0.31015419 0.68576405 0.78127305]
 [0.94382204 0.08340575 0.03389255]
 [0.07424475 0.646894   0.16500149]
 [0.04928155 0.47924493 0.47910449]]
Original:
[[ 0.         12.19955048 14.63365992 10.          0.        ]
 [ 1.          9.26437426  8.90128836  5.          0.        ]
 [ 2.         11.999338   14.66768824 12.          0.        ]
 [ 3.         13.76572845  4.42732961  5.          0.        ]
 [ 4.          7.00381844  1.64951963  7.          0.        ]
 [ 5.          8.48397668 25.34286471  9.          0.        ]
 [ 6.         11.97314028 22.76735021 10.          0.        ]
 [ 7.          9.72722249  8.98484137 15.          0.        ]
 [ 8.          9.85034325 19.24038811  9.          0.        ]
 [ 9.          6.9642481  20.20166638  9.          0.        ]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 499, in start
    self.io_loop.start()
  File "C:\ProgramData\A

# Read Generated input from File

In [20]:

outputs = np.empty(0)
with open('output.txt', "r") as file:
    for line in file:
        splitted = line.split( )
        outputs = np.append(outputs,splitted)


#print(outputs)
#n = 7
Arrival = np.zeros(n)
Burst = np.zeros(n)
Priority = np.zeros(n)
Num = np.zeros(n)
Processes = []
m = n*4
for i in range (n):
    Num =  float(outputs[4*i])
    Arrival= float(outputs[4*i+1])
    Burst = float(outputs[4*i+2])
    Priority = float(outputs[4*i+3])
    p = Process(Arrival,Burst,Priority,Num)
    Processes.append(p)

for i in range(n):
    Processes[i].Print()



1.0 12.199550475461633 14.633659917144731 10.0
2.0 9.264374259163734 8.901288358481214 5.0
3.0 11.999338000789658 14.667688240235012 12.0
4.0 13.765728450937 4.427329607619006 5.0
5.0 7.003818441327978 1.6495196296174353 7.0
6.0 8.483976675602218 25.34286471077411 9.0
7.0 11.973140279281406 22.76735021493556 10.0
8.0 9.72722248876978 8.984841373171708 15.0
9.0 9.85034325243309 19.240388105264064 9.0
10.0 6.964248096489513 20.20166637965064 9.0


# Create Graph

In [25]:
def StartGraph(title):

    root = Tk.Tk()
    
    root.title(title)

    f = Figure(figsize=(20,8), dpi=70)
    
    return f,root

def AddBar(x,y,w,f):

    ax = f.add_subplot(111)
    data = y

    ind = x
    width = w
    ind += 0.5*width

    rect = ax.bar(ind, data, width, alpha = 0.8,color=colors[int(y)-1] )
    
    return ax

def EndGraph(ax,f,root,endTime):

    ax.set_xlabel('Time')
    ax.set_ylabel('Process')
    patchList = []

    for idx,color in enumerate(colors):
        data_key = matplotlib.patches.Patch(color=color, label='P'+str(idx+1))
        patchList.append(data_key)

    ax.legend(handles=patchList)

    ax.xaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%g'))
    ax.xaxis.set_ticks(np.arange(0, endTime, int(endTime/30)))
    ax.yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%g'))
    ax.yaxis.set_ticks(np.arange(0, n+1, 1))



    canvas = FigureCanvasTkAgg(f, master=root)
    canvas.show()
    canvas.get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    Tk.mainloop()

# Non-Preemptive Highest Priority First (HPF)

In [32]:
def HPF(Processes):

    for i in range(n):
        Processes[i].reset()
    
    Processes.sort(key=lambda x: x.arrival)
    currentTime = Processes[0].arrival
    
    
    
    Processes.sort(key=lambda x: x.priority)
    Processes[:] = Processes[::-1]

    for i in range(n):
        Processes[i].Print()
        
    print(' ')
    
    i = 0
    
    #Equal priority sort according to index
    while i < n:
        priority = Processes[i].priority
        print('i=',i,' priority = ',priority)
        indices = []
        indices +=[i]
        j = i+1
        i = j
        while (j < n and  Processes[j].priority == priority):
            print('j = ',j , ' priority = ',Processes[j].priority)
            indices += [j]
            j += 1
            i = j
        if (len(indices) > 1):
            print(indices)
            print('sort')
            sortedProcesses = Processes[indices[0]:indices[-1]+1]
            for k in range(len(sortedProcesses)):
                sortedProcesses[k].Print()
            sortedProcesses.sort(key=lambda x: x.ID)
            for k in range(len(sortedProcesses)):
                sortedProcesses[k].Print()
            Processes[indices[0]:indices[-1]+1] = sortedProcesses
            del sortedProcesses[:]
        del indices[:]

    print(' ')
    for i in range(n):
        Processes[i].Print()
    

    num = 0
    
    f,root = StartGraph('HPF')
    
    while num != n:
        found = False

        for i in range(n):
            Processes[i].start(currentTime)
            if Processes[i].started and not Processes[i].finished :
                Processes[i].run(Processes[i].burst)
                ax = AddBar(x = currentTime,y = Processes[i].ID,w = Processes[i].burst,f = f)
                currentTime += Processes[i].burst
                currentTime += contextSwitching
                found = True
                num += 1
                
                break
        if (found == False):
            currentTime += 0.01


    EndGraph(ax,f,root,currentTime)
    
    
HPF(Processes)


8.0 9.72722248876978 8.984841373171708 15.0
3.0 11.999338000789658 14.667688240235012 12.0
1.0 12.199550475461633 14.633659917144731 10.0
7.0 11.973140279281406 22.76735021493556 10.0
9.0 9.85034325243309 19.240388105264064 9.0
6.0 8.483976675602218 25.34286471077411 9.0
10.0 6.964248096489513 20.20166637965064 9.0
5.0 7.003818441327978 1.6495196296174353 7.0
4.0 13.765728450937 4.427329607619006 5.0
2.0 9.264374259163734 8.901288358481214 5.0
 
i= 0  priority =  15.0
i= 1  priority =  12.0
i= 2  priority =  10.0
j =  3  priority =  10.0
[2, 3]
sort
1.0 12.199550475461633 14.633659917144731 10.0
7.0 11.973140279281406 22.76735021493556 10.0
1.0 12.199550475461633 14.633659917144731 10.0
7.0 11.973140279281406 22.76735021493556 10.0
i= 4  priority =  9.0
j =  5  priority =  9.0
j =  6  priority =  9.0
[4, 5, 6]
sort
9.0 9.85034325243309 19.240388105264064 9.0
6.0 8.483976675602218 25.34286471077411 9.0
10.0 6.964248096489513 20.20166637965064 9.0
6.0 8.483976675602218 25.34286471077411 

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.


# Round-Robin with Quantam 

In [30]:
class Queue:
    
    def __init__(self):
        self.queue = list()

    def addtoq(self,dataval):
    # Insert method to add element
        if dataval not in self.queue:
            self.queue.insert(len(self.queue),dataval)
            return True
        return False
    # Pop method to remove element
    def removefromq(self):
        if len(self.queue)>0:
            value = self.queue[0]
            del self.queue[0]
            return value
        return ("No elements in Queue!")
    def exist(self,value):
        return (value in self.queue)
    def Print(self):
        for i in self.queue:
            print(i)
        print(' ')

In [31]:
def RR(Processes):


    for i in range(n):
            Processes[i].reset()

    Processes.sort(key=lambda x: x.arrival)

    for i in range(n):
        Processes[i].Print()

    f,root = StartGraph('RR')    


    queue = Queue()
    quantam = 3.0
    currentTime = Processes[0].arrival

    print(currentTime)

    num = 0
    index = n
    QueueSize = 0

    while QueueSize != 0 or num != n:
        
        #print('Queue')
        #queue.Print()
  
        if (QueueSize != 0):
            
            index = queue.removefromq()
            
            x = currentTime
            y = Processes[index].ID
            

            if (Processes[index].remainingTime < quantam ):
                currentTime += (Processes[index].remainingTime)
                w = Processes[index].remainingTime
                QueueSize -= 1
                Processes[index].run(quantam)
                index = n
                
            else:
                currentTime += quantam
                w = quantam
                Processes[index].run(quantam)
                
            
            
            
            currentTime += contextSwitching

            
            ax = AddBar(x,y,w,f)
            
            

        #check if new process came


        if num != n:
            found = False

            for i in range(n):
                Processes[i].start(currentTime)
                if (Processes[i].started  and ( not Processes[i].finished ) and (not queue.exist(i)) and not( index == i ) ):
                    #print(i)
                    
                    print(' ')
                    queue.addtoq(i)                    
                    found = True
                    num += 1
                    QueueSize += 1


            if (found == False and QueueSize == 0):
                currentTime += 0.01    

        if not (index == n ):
            queue.addtoq(index)
            index = n
            
    EndGraph(ax,f,root,currentTime)


    print(currentTime)

RR(Processes)

10.0 6.964248096489513 20.20166637965064 9.0
5.0 7.003818441327978 1.6495196296174353 7.0
6.0 8.483976675602218 25.34286471077411 9.0
2.0 9.264374259163734 8.901288358481214 5.0
8.0 9.72722248876978 8.984841373171708 15.0
9.0 9.85034325243309 19.240388105264064 9.0
7.0 11.973140279281406 22.76735021493556 10.0
3.0 11.999338000789658 14.667688240235012 12.0
1.0 12.199550475461633 14.633659917144731 10.0
4.0 13.765728450937 4.427329607619006 5.0
6.964248096489513
 
 
 
 
 
 
 
 
 
 


C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.


397.780844633383


# Shortest Remaining Time First

In [ ]:
n =4
Temp2 = []
FinishedQueue = []
timestep = 1
xtemp = None

for i in range(n):
    Temp2.append(Processes[i])

def STRN():
    Queue = []
    Temp2.sort(key=lambda x: x.arrival)
    timer = 0 
    currentlyProcessed = None
    j = 0
    for i in range(n):
        Temp2[i].reset()
        
    f,root = StartGraph('SRTF')    
    
    while(j != n):
        for i in range(len(Temp2)):
            if(Temp2[i].start(timer)):# and not(Temp2[i].finished) #and not (Temp2[i].inQueue)): #appending processes whose time has come to run.
                Queue.append(Temp2[i])
                #Temp2[i].inQueue = True
                Temp2.remove(Temp2[i])
                break
        if (len(Queue)!=0): #getting the process with minimum burst time to run next.
            Queue.sort(key= lambda x: x.remainingTime)
            for i in range(len(Queue)):
                Queue[i].Print()
            print('****************************')
            Queue[0].run(timestep)
            
            x = timer
            y = Queue[0].ID
            w = timestep
            
            ax = AddBar(x,y,w,f)
            
            timer += timestep
            if(Queue[0].finished):
                Queue.remove(Queue[0])
                j+=1
                timer += timestep
            else:
                timer += timestep
        else:
            timer += timestep
            
    EndGraph(ax,f,root,timer)

STRN()                    

# First Come First Served

In [ ]:
Temp = []
timestep = 1

for i in range(n):
    Temp.append(Processes[i])

def FCFS():
    Queue = []
    Temp.sort(key=lambda x: x.arrival)
    timer = Temp[0].arrival
    f,root = StartGraph('FCFS')   
    for i in range(n):
        Temp[i].reset()
    j = 0;
    while(j != n):
        while (len(Queue) == 0):
            timer += 0.01
            for i in range(n):
                if(Temp[i].start(timer) and not(Temp[i].finished)):
                    Queue.append(Temp[i])
        Queue[j].run(Queue[j].burst)
        Queue[j].finished = True
        timer += Queue[j].burst
        #timer+= context switching.
        Queue[j].Print()
        print(timer)
        x = timer - Queue[j].burst
        y = Queue[j].ID
        w = Queue[j].burst
        ax = AddBar(x,y,w,f)
        j += 1
        
    EndGraph(ax,f,root,timer)
    
FCFS()