# GUI

In [65]:
filename = None
CS = None
Quantum = None
Algorithm = None

import tkinter as tk

master = tk.Tk()

v = tk.IntVar()


def get_input():
    fileName = e1.get()
    CS = e2.get()
    Quantum = e3.get()
    Algorithm = v.get()
    
    print(fileName,CS,Quantum,Algorithm)

Label(master, text="Input File Name").grid(row=0)
Label(master, text="Context Switching Time").grid(row=1)
Label(master, text="Quantum").grid(row=2)
Label(master, text="Choose an Algorithm : ").grid(row=3)

e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)

e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)


tk.Radiobutton(master, 
              text="First Come First Served.", 
              variable=v, 
              value=1).grid(row = 4)
tk.Radiobutton(master, 
              text="Hightest Priority First.",
              variable=v, 
              value=2).grid(row = 5)
tk.Radiobutton(master, 
              text="Round Robin.",
              variable=v, 
              value=3).grid(row = 6)
tk.Radiobutton(master, 
              text="Shortest Remaining Time First.",
              variable=v, 
              value=4).grid(row = 7)


Button(master, text='Start',command=get_input).grid(row=8, column=2, sticky=W)


master.mainloop()

1 2 3 4


In [23]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib, sys
matplotlib.use('TkAgg')
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk

class Process:
    arrival = 0
    burst = 0
    waiting = 0
    lastRunTime = 0
    priority = 0
    remainingTime = 0
    ID = 0
    finished = False
    started = False
    inQueue = False
    
    def __init__(self,arrival,burst,priority,ID):
        self.arrival = arrival
        self.burst = burst
        self.priority = priority
        self.remainingTime = burst
        self.ID = ID
        inQueue = False
        self.lastRunTime = 0
        
    def getTAT(self):
        return burst+waiting
    def getWTAT(self):
        return self.getTAT()/burst
    def start(self,currentTime):
        
        if(currentTime >= self.arrival):
            self.started = True
            return True
        else:
            return False
    def run(self,n):
        self.remainingTime -= n
        self.waiting += (n - self.lastRunTime)
        self.lastRunTime = n
        if (self.remainingTime <= 0):
            self.finished = True
            self.remainingTime = 0
    def wait(self,n):
        self.waitingTime += n
    def reset(self):
        self.waitingTime = 0
        self.remainingTime = self.burst
        self.finished = False
        self.started = False
        self.inQueue = False
        self.lastRunTime = 0
    def Print(self):
        print(self.ID,self.arrival,self.burst,self.remainingTime,self.priority)
    
        

inputs = np.array([])

with open("input.txt", "r") as file:
    for line in file:
        splitted = line.split( )
        inputs = np.append(inputs,splitted)

n = int(inputs[0])

colors = np.random.rand(n,3)
print(colors)

muArrival , sigmaArrival = float(inputs[1]), float(inputs[2])
muBurst , sigmaBurst = float(inputs[3]), float(inputs[4])
lamda = float(inputs[5])

Arrivals = np.random.normal(muArrival,sigmaArrival ,n)
Burst = np.random.normal(muBurst,sigmaBurst ,n)
Priority = np.random.poisson(lamda,n)
Waiting = np.zeros(Arrivals.shape)

contextSwitching = 5

fh = open("output.txt","w")

#Ouput to file the generated processes
for i in range(n):
    fh.write(str(i+1) + ' ' + str(Arrivals[i]) + ' ' + str(Burst[i]) + ' ' + str(Priority[i]) + '\n')

fh.close()


processes = np.array([range(n),Arrivals,Burst,Priority,Waiting]).transpose()
print('Original:')
print(processes)
print(' ')


[[0.36393919 0.07534443 0.8845745 ]
 [0.61048544 0.47333647 0.59496675]
 [0.96911758 0.50790485 0.81954048]
 [0.28608956 0.02322172 0.08598011]
 [0.70834375 0.065884   0.4846774 ]
 [0.43455692 0.17958199 0.80251314]
 [0.04905768 0.1148367  0.14799683]
 [0.97454325 0.5239828  0.20754946]
 [0.65378813 0.8956554  0.68404545]
 [0.91789335 0.9534337  0.32435196]]
Original:
[[ 0.          6.71087243  4.17578971  3.          0.        ]
 [ 1.          8.24850462  4.08319276  3.          0.        ]
 [ 2.          5.92191691  1.92083354  0.          0.        ]
 [ 3.          7.66042235  1.91190439  2.          0.        ]
 [ 4.         10.070206    1.00446704  2.          0.        ]
 [ 5.          9.77314887  1.93870019  2.          0.        ]
 [ 6.          7.99748133 -0.63708509  1.          0.        ]
 [ 7.          9.31505569  5.89465894  3.          0.        ]
 [ 8.         10.52240461  1.40517354  1.          0.        ]
 [ 9.          9.02930425  2.16955759  1.          0.        ]

D:\Download\ANACONDA3.6\lib\site-packages\ipykernel_launcher.py:4: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "D:\Download\ANACONDA3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Download\ANACONDA3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Download\ANACONDA3.6\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Download\ANACONDA3.6\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Download\ANACONDA3.6\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "D:\Download\ANACONDA3.

# Read Generated input from File

In [24]:

outputs = np.empty(0)
with open('output.txt', "r") as file:
    for line in file:
        splitted = line.split( )
        outputs = np.append(outputs,splitted)


#print(outputs)
#n = 7
Arrival = np.zeros(n)
Burst = np.zeros(n)
Priority = np.zeros(n)
Num = np.zeros(n)
Processes = []
m = n*4
for i in range (n):
    Num =  abs(float(outputs[4*i]))
    Arrival= abs(float(outputs[4*i+1]))
    Burst = abs(float(outputs[4*i+2]))
    Priority = abs(float(outputs[4*i+3]))
    p = Process(Arrival,Burst,Priority,Num)
    Processes.append(p)

for i in range(n):
    Processes[i].Print()



1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
3.0 5.921916910505104 1.9208335431081274 1.9208335431081274 0.0
4.0 7.660422345623199 1.911904387921882 1.911904387921882 2.0
5.0 10.070205999111161 1.004467036750857 1.004467036750857 2.0
6.0 9.773148867850422 1.9387001918605284 1.9387001918605284 2.0
7.0 7.997481325621292 0.6370850934129764 0.6370850934129764 1.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
9.0 10.522404613453041 1.405173538832095 1.405173538832095 1.0
10.0 9.029304247780711 2.1695575927310364 2.1695575927310364 1.0


# Create Graph

In [25]:
def StartGraph(title):

    root = Tk.Tk()
    
    root.title(title)

    f = Figure(figsize=(20,8), dpi=70)
    
    return f,root

def AddBar(x,y,w,f):

    ax = f.add_subplot(111)
    data = y

    ind = x
    width = w
    ind += 0.5*width

    rect = ax.bar(ind, data, width, alpha = 0.8,color=colors[int(y)-1] )
    
    return ax

def EndGraph(ax,f,root,endTime):

    ax.set_xlabel('Time')
    ax.set_ylabel('Process')
    patchList = []

    for idx,color in enumerate(colors):
        data_key = matplotlib.patches.Patch(color=color, label='P'+str(idx+1))
        patchList.append(data_key)

    ax.legend(handles=patchList)

    ax.xaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%g'))
    ax.xaxis.set_ticks(np.arange(0, endTime, int(endTime/30)))
    ax.yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%g'))
    ax.yaxis.set_ticks(np.arange(0, n+1, 1))



    canvas = FigureCanvasTkAgg(f, master=root)
    canvas.show()
    canvas.get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    Tk.mainloop()

# Non-Preemptive Highest Priority First (HPF)

In [27]:
def HPF(Processes):

    for i in range(n):
        Processes[i].reset()
    
    Processes.sort(key=lambda x: x.arrival)
    currentTime = Processes[0].arrival
    
    
    
    Processes.sort(key=lambda x: x.priority)
    Processes[:] = Processes[::-1]

    for i in range(n):
        Processes[i].Print()
        
    print(' ')
    
    i = 0
    
    #Equal priority sort according to index
    while i < n:
        priority = Processes[i].priority
        print('i=',i,' priority = ',priority)
        indices = []
        indices +=[i]
        j = i+1
        i = j
        while (j < n and  Processes[j].priority == priority):
            print('j = ',j , ' priority = ',Processes[j].priority)
            indices += [j]
            j += 1
            i = j
        if (len(indices) > 1):
            print(indices)
            print('sort')
            sortedProcesses = Processes[indices[0]:indices[-1]+1]
            for k in range(len(sortedProcesses)):
                sortedProcesses[k].Print()
            sortedProcesses.sort(key=lambda x: x.ID)
            for k in range(len(sortedProcesses)):
                sortedProcesses[k].Print()
            Processes[indices[0]:indices[-1]+1] = sortedProcesses
            del sortedProcesses[:]
        del indices[:]

    print(' ')
    for i in range(n):
        Processes[i].Print()
    

    num = 0
    
    f,root = StartGraph('HPF')
    
    while num != n:
        found = False

        for i in range(n):
            Processes[i].start(currentTime)
            if Processes[i].started and not Processes[i].finished :
                Processes[i].run(Processes[i].burst)
                ax = AddBar(x = currentTime,y = Processes[i].ID,w = Processes[i].burst,f = f)
                currentTime += Processes[i].burst
                currentTime += contextSwitching
                found = True
                num += 1
                
                break
        if (found == False):
            currentTime += 0.01


    EndGraph(ax,f,root,currentTime)
    
    
HPF(Processes)


8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
5.0 10.070205999111161 1.004467036750857 1.004467036750857 2.0
6.0 9.773148867850422 1.9387001918605284 1.9387001918605284 2.0
4.0 7.660422345623199 1.911904387921882 1.911904387921882 2.0
9.0 10.522404613453041 1.405173538832095 1.405173538832095 1.0
10.0 9.029304247780711 2.1695575927310364 2.1695575927310364 1.0
7.0 7.997481325621292 0.6370850934129764 0.6370850934129764 1.0
3.0 5.921916910505104 1.9208335431081274 1.9208335431081274 0.0
 
i= 0  priority =  3.0
j =  1  priority =  3.0
j =  2  priority =  3.0
[0, 1, 2]
sort
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
2.0 8.248504620510108 4.0831927614

D:\Download\ANACONDA3.6\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
D:\Download\ANACONDA3.6\lib\site-packages\ipykernel_launcher.py:44: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.


# Round-Robin with Quantam 

In [28]:
class Queue:
    
    def __init__(self):
        self.queue = list()

    def addtoq(self,dataval):
    # Insert method to add element
        if dataval not in self.queue:
            self.queue.insert(len(self.queue),dataval)
            return True
        return False
    # Pop method to remove element
    def removefromq(self):
        if len(self.queue)>0:
            value = self.queue[0]
            del self.queue[0]
            return value
        return ("No elements in Queue!")
    def exist(self,value):
        return (value in self.queue)
    def Print(self):
        for i in self.queue:
            print(i)
        print(' ')

In [29]:
def RR(Processes):


    for i in range(n):
            Processes[i].reset()

    Processes.sort(key=lambda x: x.arrival)

    for i in range(n):
        Processes[i].Print()

    f,root = StartGraph('RR')    


    queue = Queue()
    quantam = 3.0
    currentTime = Processes[0].arrival

    print(currentTime)

    num = 0
    index = n
    QueueSize = 0

    while QueueSize != 0 or num != n:
        
        #print('Queue')
        #queue.Print()
  
        if (QueueSize != 0):
            
            index = queue.removefromq()
            
            x = currentTime
            y = Processes[index].ID
            

            if (Processes[index].remainingTime < quantam ):
                currentTime += (Processes[index].remainingTime)
                w = Processes[index].remainingTime
                QueueSize -= 1
                Processes[index].run(quantam)
                index = n
                
            else:
                currentTime += quantam
                w = quantam
                Processes[index].run(quantam)
                
            
            
            
            currentTime += contextSwitching

            
            ax = AddBar(x,y,w,f)
            
            

        #check if new process came


        if num != n:
            found = False

            for i in range(n):
                Processes[i].start(currentTime)
                if (Processes[i].started  and ( not Processes[i].finished ) and (not queue.exist(i)) and not( index == i ) ):
                    #print(i)
                    
                    print(' ')
                    queue.addtoq(i)                    
                    found = True
                    num += 1
                    QueueSize += 1


            if (found == False and QueueSize == 0):
                currentTime += 0.01    

        if not (index == n ):
            queue.addtoq(index)
            index = n
            
    EndGraph(ax,f,root,currentTime)


    print(currentTime)

RR(Processes)

3.0 5.921916910505104 1.9208335431081274 1.9208335431081274 0.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
4.0 7.660422345623199 1.911904387921882 1.911904387921882 2.0
7.0 7.997481325621292 0.6370850934129764 0.6370850934129764 1.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
10.0 9.029304247780711 2.1695575927310364 2.1695575927310364 1.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
6.0 9.773148867850422 1.9387001918605284 1.9387001918605284 2.0
5.0 10.070205999111161 1.004467036750857 1.004467036750857 2.0
9.0 10.522404613453041 1.405173538832095 1.405173538832095 1.0
5.921916910505104
 
 
 
 
 
 
 
 
 
 


D:\Download\ANACONDA3.6\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
D:\Download\ANACONDA3.6\lib\site-packages\ipykernel_launcher.py:44: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.


96.06327969922418


# Shortest Remaining Time First

In [30]:
n = 10
Temp2 = []
FinishedQueue = []
timestep = 1
xtemp = None

for i in range(n):
    Temp2.append(Processes[i])

def STRN():
    Queue = []
    Temp2.sort(key=lambda x: x.arrival)
    f,root = StartGraph('SRTF')
    timer = 0 
    currentlyProcessed = None
    j = 0
    for i in range(n):
        Temp2[i].reset()
    while(j != n):
        for i in range(len(Temp2)):
            if(Temp2[i].start(timer)):# and not(Temp2[i].finished) #and not (Temp2[i].inQueue)): #appending processes whose time has come to run.
                Queue.append(Temp2[i])
                #Temp2[i].inQueue = True
                Temp2.remove(Temp2[i])
                break
        if (len(Queue)!=0): #getting the process with minimum burst time to run next.
            Queue.sort(key= lambda x: x.remainingTime)
            for i in range(len(Queue)):
                Queue[i].Print()
            print('****************************')
            x = timer
            w = min(timestep,Queue[0].remainingTime)
            timer += min(timestep,Queue[0].remainingTime)
            Queue[0].run(timestep)
            y = Queue[0].ID
            ax = AddBar(x,y,w,f)
            if(Queue[0].finished):
                Queue.remove(Queue[0])
                j+=1
        else:
            timer += timestep
    EndGraph(ax,f,root,timer)
STRN()                    

3.0 5.921916910505104 1.9208335431081274 1.9208335431081274 0.0
****************************
3.0 5.921916910505104 1.9208335431081274 0.9208335431081274 0.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
****************************
4.0 7.660422345623199 1.911904387921882 1.911904387921882 2.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
****************************
7.0 7.997481325621292 0.6370850934129764 0.6370850934129764 1.0
4.0 7.660422345623199 1.911904387921882 0.911904387921882 2.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
****************************
4.0 7.660422345623199 1.911904387921882 0.911904387921882 2.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
****************************
10.0 9.029304247780711 2.1695575927310364 2.1695575927310364 1.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 

D:\Download\ANACONDA3.6\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)


6.0 9.773148867850422 1.9387001918605284 1.9387001918605284 2.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
****************************
6.0 9.773148867850422 1.9387001918605284 0.9387001918605284 2.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
****************************
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
****************************
2.0 8.248504620510108 4.083192761438788 3.083192761438788 3.0
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
****************************
2.0 8.248504

D:\Download\ANACONDA3.6\lib\site-packages\ipykernel_launcher.py:44: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.


# First Come First Served

In [32]:


def FCFS(Processes):
    
    Temp = []
    timestep = 1

    for i in range(n):
        Temp.append(Processes[i])
    Queue = []
    Temp.sort(key=lambda x: x.arrival)
    f,root = StartGraph('FCFS')
    timer = 0
    for i in range(n):
        Temp[i].reset()
    j = 0;
    while(j != n):
        for i in range(n):
            if(Temp[i].start(timer) and not(Temp[i].finished) and not(Temp[i].inQueue)):
                Queue.append(Temp[i])
                Temp[i].inQueue = True
        for i in range(len(Queue)):
            Queue[i].Print()
        print('**************************')
        if(len(Queue)!=0):
            Queue[0].run(Queue[0].burst)
            Queue[0].finished = True
            timer += Queue[0].burst
            #timer+= context switching.
            #Queue[0].Print()
            #print(timer)
            x = timer - Queue[0].burst
            y = Queue[0].ID
            w = Queue[0].burst
            ax = AddBar(x,y,w,f)
            j += 1
            del Queue[0]
            
        else:
            timer+=timestep
            
    EndGraph(ax,f,root,timer)
FCFS(Processes)

**************************
**************************
**************************
**************************
**************************
**************************
3.0 5.921916910505104 1.9208335431081274 1.9208335431081274 0.0
**************************
1.0 6.710872426267519 4.175789705407547 4.175789705407547 3.0
4.0 7.660422345623199 1.911904387921882 1.911904387921882 2.0
**************************
4.0 7.660422345623199 1.911904387921882 1.911904387921882 2.0
7.0 7.997481325621292 0.6370850934129764 0.6370850934129764 1.0
2.0 8.248504620510108 4.083192761438788 4.083192761438788 3.0
10.0 9.029304247780711 2.1695575927310364 2.1695575927310364 1.0
8.0 9.315055688209217 5.894658937255233 5.894658937255233 3.0
6.0 9.773148867850422 1.9387001918605284 1.9387001918605284 2.0
5.0 10.070205999111161 1.004467036750857 1.004467036750857 2.0
9.0 10.522404613453041 1.405173538832095 1.405173538832095 1.0
**************************
7.0 7.997481325621292 0.6370850934129764 0.6370850934129764 1.0


D:\Download\ANACONDA3.6\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
D:\Download\ANACONDA3.6\lib\site-packages\ipykernel_launcher.py:44: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.


# GUI 

1
2
3
1
1
2
3
2
