In [1]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib, sys
matplotlib.use('TkAgg')
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk

class Process:
    arrival = 0
    burst = 0
    waiting = 0
    priority = 0
    remainingTime = 0
    ID = 0
    finished = False
    started = False
    inQueue = False
    
    def __init__(self,arrival,burst,priority,ID):
        self.arrival = arrival
        self.burst = burst
        self.priority = priority
        self.remainingTime = burst
        self.ID = ID
        inQueue = False
        
    def getTAT(self):
        return burst+waiting
    def getWTAT(self):
        return self.getTAT()/burst
    def start(self,currentTime):
        if(currentTime >= self.arrival):
            self.started = True
    def run(self,n):
        self.remainingTime -= n
        if (self.remainingTime <= 0):
            self.finished = True
            self.remainingTime = 0
    def wait(self,n):
        self.waitingTime += n
    def reset(self):
        self.waitingTime = 0
        self.remainingTime = self.burst
        self.finished = False
        self.started = False
        self.inQueue = False
    def Print(self):
        print(self.ID,self.arrival,self.burst,self.priority)
        
    def __lt__(self, other):
        #priority
        '''
        if (self.priority < other.priority ):
            return True
        if (self.priority == other.priority ):
            return (self.ID > other.ID )
        return False
    '''
        #arrival
        return (self.arrival< other.arrival)
    
        

inputs = np.array([])

with open("input.txt", "r") as file:
    for line in file:
        splitted = line.split( )
        inputs = np.append(inputs,splitted)

n = int(inputs[0])

colors = np.random.rand(n,3)
print(colors)

muArrival , sigmaArrival = float(inputs[1]), float(inputs[2])
muBurst , sigmaBurst = float(inputs[3]), float(inputs[4])
lamda = float(inputs[5])

Arrivals = np.random.normal(muArrival,sigmaArrival ,n)
Burst = np.random.normal(muBurst,sigmaBurst ,n)
Priority = np.random.poisson(lamda,n)
Waiting = np.zeros(Arrivals.shape)

contextSwitching = 5

fh = open("output.txt","w")

#Ouput to file the generated processes
for i in range(n):
    fh.write(str(i+1) + ' ' + str(Arrivals[i]) + ' ' + str(Burst[i]) + ' ' + str(Priority[i]) + '\n')

fh.close()


processes = np.array([range(n),Arrivals,Burst,Priority,Waiting]).transpose()
print('Original:')
print(processes)
print(' ')


[[0.15085167 0.55566226 0.9630047 ]
 [0.02019212 0.67147765 0.0762998 ]
 [0.3855128  0.24301312 0.6344265 ]
 [0.07725403 0.77898501 0.2922131 ]
 [0.7458666  0.51523483 0.87110749]
 [0.09716986 0.20297197 0.11079187]
 [0.17535849 0.72431353 0.74197934]]
Original:
[[ 0.          9.00057736 13.66160767  6.          0.        ]
 [ 1.          9.77160495  2.99164838  8.          0.        ]
 [ 2.         11.08803943 10.48253242 13.          0.        ]
 [ 3.          8.58119305  8.50300856  9.          0.        ]
 [ 4.          9.6429725  11.48758992 12.          0.        ]
 [ 5.         10.9720592  10.79337047  6.          0.        ]
 [ 6.          6.73126958 15.82555532  6.          0.        ]]
 


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 499, in start
    self.io_loop.start()
  File "C:\ProgramData\A

# Read Generated input from File

In [2]:

outputs = np.empty(0)
with open('output.txt', "r") as file:
    for line in file:
        splitted = line.split( )
        outputs = np.append(outputs,splitted)


#print(outputs)
n = 7
Arrival = np.zeros(n)
Burst = np.zeros(n)
Priority = np.zeros(n)
Num = np.zeros(n)
Processes = []
m = n*4
for i in range (n):
    Num =  float(outputs[4*i])
    Arrival= float(outputs[4*i+1])
    Burst = float(outputs[4*i+2])
    Priority = float(outputs[4*i+3])
    p = Process(Arrival,Burst,Priority,Num)
    Processes.append(p)

for i in range(n):
    Processes[i].Print()



1.0 9.000577363230164 13.661607668711717 6.0
2.0 9.771604952477631 2.9916483846771857 8.0
3.0 11.088039425562739 10.48253241913648 13.0
4.0 8.581193049345869 8.503008558561037 9.0
5.0 9.642972497583786 11.48758992006531 12.0
6.0 10.972059202421953 10.793370465539459 6.0
7.0 6.7312695848726225 15.825555322768787 6.0


# Create Graph

In [3]:
def StartGraph():

    root = Tk.Tk()

    f = Figure(figsize=(20,8), dpi=70)
    
    return f,root

def AddBar(x,y,w,f):

    ax = f.add_subplot(111)
    data = y

    ind = x
    width = w
    ind += 0.5*width

    rect = ax.bar(ind, data, width, alpha = 0.8,color=colors[int(data)-1] )
    
    return ax

def EndGraph(ax,f,root):

    ax.set_xlabel('Time')
    ax.set_ylabel('Process')
    patchList = []

    for idx,color in enumerate(colors):
        data_key = matplotlib.patches.Patch(color=color, label='P'+str(idx+1))
        patchList.append(data_key)

    ax.legend(handles=patchList)

    ax.xaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%g'))
    #ax.xaxis.set_ticks(np.arange(0, currentTime, 4))
    ax.yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%g'))
    ax.yaxis.set_ticks(np.arange(0, n+1, 1))



    canvas = FigureCanvasTkAgg(f, master=root)
    canvas.show()
    canvas.get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    Tk.mainloop()

# Non-Preemptive Highest Priority First (HPF)

In [ ]:
def HPF(Processes):

    for i in range(n):
        Processes[i].reset()
    
    Processes = np.sort(Processes, axis = None)
    #Processes.sort(key = lambda x: x.priority)
    Processes[:] = Processes[::-1]
    
    
    order = []


    currentTime = 0
    num = 0
    print(order)
    
    f,root = StartGraph()
    
    while num != n:
        found = False

        for i in range(n):
            Processes[i].start(currentTime)
            if not Processes[i].finished :
                Processes[i].run(Processes[i].burst)
                print(Processes[i].ID)
                print(currentTime,i+1,Processes[i].burst,f)
                ax = AddBar(x = currentTime,y = Processes[i].ID,w = Processes[i].burst,f = f)
                currentTime += Processes[i].burst
                currentTime += contextSwitching
                found = True
                num += 1
                
                break
        if (found == False):
            currentTime += 0.01


    for i in range(n):
        Processes[i].Print()
    EndGraph(ax,f,root)
    
    
HPF(Processes)


In [ ]:
class Queue:
    
    def __init__(self):
        self.queue = list()

    def addtoq(self,dataval):
    # Insert method to add element
        if dataval not in self.queue:
            self.queue.insert(len(self.queue),dataval)
            return True
        return False
    # Pop method to remove element
    def removefromq(self):
        if len(self.queue)>0:
            value = self.queue[0]
            del self.queue[0]
            return value
        return ("No elements in Queue!")
    def exist(self,value):
        return (value in self.queue)
    def Print(self):
        for i in self.queue:
            print(i)
        print(' ')

# Round-Robin with Quantam 

In [ ]:
def RR(Processes):


    for i in range(n):
            Processes[i].reset()

    Processes = np.sort(Processes, axis = None)
    #Processes.sort(key = lambda x: x.priority)

    for i in range(n):
        Processes[i].Print()

    f,root = StartGraph()    


    queue = Queue()
    #remainingTime = Queue()
    quantam = 3.0
    currentTime = Processes[0].arrival

    print(currentTime)

    num = 0
    index = n
    QueueSize = 0

    while QueueSize != 0 or num != n:
        
        print('Queue')
        queue.Print()
  
        if (QueueSize != 0):
            
            index = queue.removefromq()
            
            x = currentTime
            y = Processes[index].ID
            

            if (Processes[index].remainingTime < quantam ):
                currentTime += (Processes[index].remainingTime)
                w = Processes[index].remainingTime
                QueueSize -= 1
                Processes[index].run(quantam)
                index = n
                
            else:
                currentTime += quantam
                w = quantam
                Processes[index].run(quantam)
                
            
            
            
            currentTime += contextSwitching

            
            ax = AddBar(x,y,w,f)
            
            

        #check if new process came


        if num != n:
            found = False

            for i in range(n):
                Processes[i].start(currentTime)
                if ( not Processes[i].finished ) and (not queue.exist(i) ):
                    queue.addtoq(i)                    
                    found = True
                    num += 1
                    QueueSize += 1

                    break
            if (found == False and QueueSize == 0):
                currentTime += 0.01    

        if not (index == n ):
            queue.addtoq(index)
            index = n
    EndGraph(ax,f,root)


    print(currentTime)

RR(Processes)

# Shortest Remaining Time First

In [ ]:
n =4
Temp2 = []
FinishedQueue = []
timestep = 1
xtemp = None

for i in range(n):
    Temp2.append(Processes[i])

def STRN():
    Queue = []
    Temp2.sort(key=lambda x: x.arrival)
    timer = 0 
    currentlyProcessed = None
    j = 0
    for i in range(n):
        Temp2[i].reset()
    while(j != n):
        for i in range(len(Temp2)):
            if(Temp2[i].start(timer)):# and not(Temp2[i].finished) #and not (Temp2[i].inQueue)): #appending processes whose time has come to run.
                Queue.append(Temp2[i])
                #Temp2[i].inQueue = True
                Temp2.remove(Temp2[i])
                break
        if (len(Queue)!=0): #getting the process with minimum burst time to run next.
            Queue.sort(key= lambda x: x.remainingTime)
            for i in range(len(Queue)):
                Queue[i].Print()
            print('****************************')
            Queue[0].run(timestep)
            timer += timestep
            if(Queue[0].finished):
                Queue.remove(Queue[0])
                j+=1
                timer += timestep
            else:
                timer += timestep
        else:
            timer += timestep

STRN()                    

# First Come First Served

In [ ]:
Temp = []
timestep = 1

for i in range(n):
    Temp.append(Processes[i])

def FCFS():
    Queue = []
    Temp.sort(key=lambda x: x.arrival)
    timer = Temp[0].arrival
    f,root = StartGraph()   
    for i in range(n):
        Temp[i].reset()
    j = 0;
    while(j != n):
        while (len(Queue) == 0):
            timer += 0.01
            for i in range(n):
                if(Temp[i].start(timer) and not(Temp[i].finished)):
                    Queue.append(Temp[i])
        Queue[j].run(Queue[j].burst)
        Queue[j].finished = True
        timer += Queue[j].burst
        #timer+= context switching.
        Queue[j].Print()
        print(timer)
        x = timer - Queue[j].burst
        y = Queue[j].ID
        w = Queue[j].burst
        ax = AddBar(x,y,w,f)
        j += 1
        
    EndGraph(ax,f,root)
    
FCFS()